### ISSUE TITLE
windows下出错，Invalid regular expression

### ISSUE THREAD

**Issue by formreact** [WhatAKitty/react-script-antd-pro#2]
yarn start v0.21.3
$ react-app-rewired start
D:\AntDesign\react-script-antd-pro\react-script-antd-pro-master\node_modules\react-app-rewire-less-modules\index.js:51
```
include = new RegExp(`${path.sep}src${path.sep}components${path.sep}`),
            ^

SyntaxError: Invalid regular expression: /\src\components\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at createRewireLess (D:\AntDesign\react-script-antd-pro\react-script-antd-pro-master\node_modules\react-app-rewire-less-modules\index.js:51:13)
    at Object.<anonymous> (D:\AntDesign\react-script-antd-pro\react-script-antd-pro-master\node_modules\react-app-rewire-less-modules\index.js:94:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```

能否修复下，谢谢

**Comment by WhatAKitty** [comment]
目前没有windows环境，我具体查一下问题

**Comment by WhatAKitty** [comment]
已经修复。
具体做法：
* 删除`node_modules`、`yarn-lock.json`以及`package-lock.json`
* 重新`yarn install` 或者 `npm install`
* `yarn start`

**Comment by andriijas** [comment]
@WhatAKitty you can use getLoader and name matcher from rewire to simplify code if you want to: https://github.com/andriijas/react-app-rewire-less-modules/blob/master/index.js
